/* Generated By:JavaCC: Do not edit this line. ISO8601ParserConstants.java */
package com.sun.tranquilo.datatype;

public interface ISO8601ParserConstants {

  int EOF = 0;
  int digit = 1;
  int digits = 2;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<digit>",
    "<digits>",
    "\".\"",
    "\"-\"",
    "\"P\"",
    "\"T\"",
    "\"Y\"",
    "\"M\"",
    "\"D\"",
    "\"H\"",
    "\"S\"",
    "\"Z\"",
    "\"+\"",
    "\":\"",
    "\"--\"",
    "\"---\"",
  };

}
