/* Generated By:JavaCC: Do not edit this line. UriReferenceParserTokenManager.java */
package com.sun.tranquilo.datatype;
import java.io.*;

public class UriReferenceParserTokenManager implements UriReferenceParserConstants
{
private final int jjMoveStringLiteralDfa0_0()
{
   return jjMoveNfa_0(0, 0);
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 312;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x2bff7fd200000000L & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAddStates(0, 4);
                  }
                  else if (curChar == 37)
                     jjCheckNAddTwoStates(310, 287);
                  else if (curChar == 47)
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAddStates(5, 10);
                  }
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 150;
                  break;
               case 1:
                  if ((0x3ff680000000000L & l) != 0L)
                     jjAddStates(11, 12);
                  break;
               case 2:
                  if (curChar == 58)
                     jjAddStates(13, 16);
                  break;
               case 3:
                  if (curChar != 47)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(17, 27);
                  break;
               case 4:
                  if ((0x2fff7fd200000000L & l) != 0L)
                     jjCheckNAddStates(28, 30);
                  break;
               case 5:
                  if (curChar == 37)
                     jjCheckNAdd(6);
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 7:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(28, 30);
                  break;
               case 9:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(10, 12);
                  break;
               case 10:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(11, 12);
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(12);
                  break;
               case 12:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(14, 16);
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(15, 16);
                  break;
               case 15:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(16);
                  break;
               case 16:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 17:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(18, 20);
                  break;
               case 18:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(19, 20);
                  break;
               case 19:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(20);
                  break;
               case 20:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 21:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(22, 24);
                  break;
               case 22:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(23, 24);
                  break;
               case 23:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(24);
                  break;
               case 24:
                  if (curChar != 58)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(31, 34);
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(31, 34);
                  break;
               case 26:
                  if (curChar != 47)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(35, 40);
                  break;
               case 27:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 28:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(35, 40);
                  break;
               case 30:
                  if ((0x27ff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(35, 40);
                  break;
               case 31:
                  if (curChar != 59)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(41, 46);
                  break;
               case 32:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 33:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 34:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(41, 46);
                  break;
               case 35:
                  if ((0x27ff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(41, 46);
                  break;
               case 36:
                  if (curChar != 47)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(47, 52);
                  break;
               case 37:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 38:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 39:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(47, 52);
                  break;
               case 40:
                  if ((0x27ff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(47, 52);
                  break;
               case 41:
                  if (curChar != 59)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(53, 58);
                  break;
               case 42:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 43:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 44:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(53, 58);
                  break;
               case 45:
                  if ((0x27ff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(53, 58);
                  break;
               case 46:
                  if (curChar != 63)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(59, 61);
                  break;
               case 47:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(59, 61);
                  break;
               case 50:
                  if ((0xafffffd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(59, 61);
                  break;
               case 51:
                  if (curChar != 35)
                     break;
                  kind = 46;
                  jjCheckNAddTwoStates(52, 55);
                  break;
               case 52:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 53:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 54:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddTwoStates(52, 55);
                  break;
               case 55:
                  if ((0xafffffd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddTwoStates(52, 55);
                  break;
               case 57:
                  if (curChar == 58)
                     jjCheckNAddStates(62, 64);
                  break;
               case 58:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(65, 67);
                  break;
               case 59:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(68, 70);
                  break;
               case 60:
               case 66:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(71, 73);
                  break;
               case 61:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(62, 63);
                  break;
               case 63:
                  if (curChar == 58)
                     jjCheckNAddTwoStates(64, 67);
                  break;
               case 64:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(74, 76);
                  break;
               case 65:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(77, 79);
                  break;
               case 67:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(68, 70);
                  break;
               case 68:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(69, 70);
                  break;
               case 69:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(70);
                  break;
               case 70:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 71:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(72, 74);
                  break;
               case 72:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(73, 74);
                  break;
               case 73:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(74);
                  break;
               case 74:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 75:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(76, 78);
                  break;
               case 76:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(77, 78);
                  break;
               case 77:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(78);
                  break;
               case 78:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 79:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(80, 62);
                  break;
               case 80:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(81, 62);
                  break;
               case 81:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(62);
                  break;
               case 82:
                  if (curChar == 58)
                     jjCheckNAdd(67);
                  break;
               case 83:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 84:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(80, 85);
                  break;
               case 85:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(86, 88);
                  break;
               case 86:
               case 91:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(89, 91);
                  break;
               case 87:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(62, 88);
                  break;
               case 88:
                  if (curChar == 58)
                     jjCheckNAddTwoStates(89, 67);
                  break;
               case 89:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(92, 94);
                  break;
               case 90:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(95, 97);
                  break;
               case 92:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(98, 100);
                  break;
               case 93:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(101, 103);
                  break;
               case 94:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(95, 108);
                  break;
               case 95:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 96:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(104, 106);
                  break;
               case 97:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(107, 109);
                  break;
               case 98:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(110, 112);
                  break;
               case 99:
                  if (curChar == 58)
                     jjCheckNAddStates(113, 115);
                  break;
               case 100:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(116, 118);
                  break;
               case 101:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(119, 121);
                  break;
               case 102:
               case 107:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(122, 124);
                  break;
               case 103:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(62, 104);
                  break;
               case 104:
                  if (curChar == 58)
                     jjCheckNAddTwoStates(105, 67);
                  break;
               case 105:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(125, 127);
                  break;
               case 106:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(128, 130);
                  break;
               case 108:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 110:
                  if ((0x3ff200000000000L & l) != 0L)
                     jjAddStates(131, 132);
                  break;
               case 111:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(112, 24);
                  break;
               case 112:
                  if (curChar == 46)
                     jjCheckNAdd(24);
                  break;
               case 113:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(133, 135);
                  break;
               case 114:
                  if ((0x3ff200000000000L & l) != 0L)
                     jjCheckNAddTwoStates(114, 115);
                  break;
               case 115:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(116);
                  break;
               case 116:
                  if (curChar == 46)
                     jjCheckNAddTwoStates(109, 113);
                  break;
               case 117:
                  if ((0x2fff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(136, 140);
                  break;
               case 118:
                  if (curChar == 37)
                     jjCheckNAdd(119);
                  break;
               case 119:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 120:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(136, 140);
                  break;
               case 121:
                  if (curChar == 37)
                     jjCheckNAddTwoStates(6, 119);
                  break;
               case 122:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 123:
                  if (curChar != 47)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(141, 146);
                  break;
               case 124:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 125:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 126:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(141, 146);
                  break;
               case 127:
                  if ((0x27ff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(141, 146);
                  break;
               case 128:
                  if (curChar != 59)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(147, 152);
                  break;
               case 129:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 130:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 131:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(147, 152);
                  break;
               case 132:
                  if ((0x27ff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(147, 152);
                  break;
               case 133:
                  if (curChar != 47)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(153, 158);
                  break;
               case 134:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 135;
                  break;
               case 135:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 136:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(153, 158);
                  break;
               case 137:
                  if ((0x27ff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(153, 158);
                  break;
               case 138:
                  if (curChar != 59)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(159, 164);
                  break;
               case 139:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 140:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 141;
                  break;
               case 141:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(159, 164);
                  break;
               case 142:
                  if ((0x27ff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(159, 164);
                  break;
               case 143:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 144:
               case 147:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(145);
                  break;
               case 145:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(165, 167);
                  break;
               case 146:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 147;
                  break;
               case 148:
                  if ((0xafffffd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(165, 167);
                  break;
               case 149:
                  if ((0xafff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(165, 167);
                  break;
               case 150:
                  if (curChar != 47)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(168, 178);
                  break;
               case 151:
                  if ((0x2fff7fd200000000L & l) != 0L)
                     jjCheckNAddStates(179, 181);
                  break;
               case 152:
                  if (curChar == 37)
                     jjCheckNAdd(153);
                  break;
               case 153:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 154:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(179, 181);
                  break;
               case 156:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(157, 159);
                  break;
               case 157:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(158, 159);
                  break;
               case 158:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(159);
                  break;
               case 159:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 160;
                  break;
               case 160:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(161, 163);
                  break;
               case 161:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(162, 163);
                  break;
               case 162:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(163);
                  break;
               case 163:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 164;
                  break;
               case 164:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(165, 167);
                  break;
               case 165:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(166, 167);
                  break;
               case 166:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(167);
                  break;
               case 167:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 168:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(169, 171);
                  break;
               case 169:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(170, 171);
                  break;
               case 170:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(171);
                  break;
               case 171:
                  if (curChar != 58)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(182, 185);
                  break;
               case 172:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(182, 185);
                  break;
               case 173:
                  if (curChar != 47)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(186, 191);
                  break;
               case 174:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 175;
                  break;
               case 175:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 176;
                  break;
               case 176:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(186, 191);
                  break;
               case 177:
                  if ((0x27ff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(186, 191);
                  break;
               case 178:
                  if (curChar != 59)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(192, 197);
                  break;
               case 179:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 180;
                  break;
               case 180:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 181;
                  break;
               case 181:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(192, 197);
                  break;
               case 182:
                  if ((0x27ff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(192, 197);
                  break;
               case 183:
                  if (curChar != 47)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(198, 203);
                  break;
               case 184:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 185;
                  break;
               case 185:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 186;
                  break;
               case 186:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(198, 203);
                  break;
               case 187:
                  if ((0x27ff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(198, 203);
                  break;
               case 188:
                  if (curChar != 59)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(204, 209);
                  break;
               case 189:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 190;
                  break;
               case 190:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 191;
                  break;
               case 191:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(204, 209);
                  break;
               case 192:
                  if ((0x27ff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(204, 209);
                  break;
               case 193:
                  if (curChar != 63)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(210, 212);
                  break;
               case 194:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 195;
                  break;
               case 195:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 196;
                  break;
               case 196:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(210, 212);
                  break;
               case 197:
                  if ((0xafffffd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(210, 212);
                  break;
               case 199:
                  if (curChar == 58)
                     jjCheckNAddStates(213, 215);
                  break;
               case 200:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(216, 218);
                  break;
               case 201:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(219, 221);
                  break;
               case 202:
               case 208:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(222, 224);
                  break;
               case 203:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(204, 205);
                  break;
               case 205:
                  if (curChar == 58)
                     jjCheckNAddTwoStates(206, 209);
                  break;
               case 206:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(225, 227);
                  break;
               case 207:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(228, 230);
                  break;
               case 209:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(210, 212);
                  break;
               case 210:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(211, 212);
                  break;
               case 211:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(212);
                  break;
               case 212:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 213;
                  break;
               case 213:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(214, 216);
                  break;
               case 214:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(215, 216);
                  break;
               case 215:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(216);
                  break;
               case 216:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 217;
                  break;
               case 217:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(218, 220);
                  break;
               case 218:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(219, 220);
                  break;
               case 219:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(220);
                  break;
               case 220:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 221;
                  break;
               case 221:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(222, 204);
                  break;
               case 222:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(223, 204);
                  break;
               case 223:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(204);
                  break;
               case 224:
                  if (curChar == 58)
                     jjCheckNAdd(209);
                  break;
               case 225:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 199;
                  break;
               case 226:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(231, 236);
                  break;
               case 227:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(237, 239);
                  break;
               case 228:
               case 233:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(240, 242);
                  break;
               case 229:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(204, 230);
                  break;
               case 230:
                  if (curChar == 58)
                     jjCheckNAddTwoStates(231, 209);
                  break;
               case 231:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(243, 245);
                  break;
               case 232:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(246, 248);
                  break;
               case 234:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(249, 251);
                  break;
               case 235:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(252, 254);
                  break;
               case 236:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(237, 250);
                  break;
               case 237:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 238;
                  break;
               case 238:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(255, 257);
                  break;
               case 239:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(258, 260);
                  break;
               case 240:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(261, 263);
                  break;
               case 241:
                  if (curChar == 58)
                     jjCheckNAddStates(264, 266);
                  break;
               case 242:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(267, 269);
                  break;
               case 243:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(270, 272);
                  break;
               case 244:
               case 249:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(273, 275);
                  break;
               case 245:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(204, 246);
                  break;
               case 246:
                  if (curChar == 58)
                     jjCheckNAddTwoStates(247, 209);
                  break;
               case 247:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(276, 278);
                  break;
               case 248:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(279, 281);
                  break;
               case 250:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 241;
                  break;
               case 252:
                  if ((0x3ff200000000000L & l) != 0L)
                     jjAddStates(282, 283);
                  break;
               case 253:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(254, 171);
                  break;
               case 254:
                  if (curChar == 46)
                     jjCheckNAdd(171);
                  break;
               case 255:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(284, 286);
                  break;
               case 256:
                  if ((0x3ff200000000000L & l) != 0L)
                     jjCheckNAddTwoStates(256, 257);
                  break;
               case 257:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(258);
                  break;
               case 258:
                  if (curChar == 46)
                     jjCheckNAddTwoStates(251, 255);
                  break;
               case 259:
                  if ((0x2fff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(287, 291);
                  break;
               case 260:
                  if (curChar == 37)
                     jjCheckNAdd(261);
                  break;
               case 261:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 262;
                  break;
               case 262:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(287, 291);
                  break;
               case 263:
                  if (curChar == 37)
                     jjCheckNAddTwoStates(153, 261);
                  break;
               case 264:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 150;
                  break;
               case 265:
                  if (curChar != 47)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(5, 10);
                  break;
               case 266:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 267;
                  break;
               case 267:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 268;
                  break;
               case 268:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(5, 10);
                  break;
               case 269:
                  if ((0x27ff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(5, 10);
                  break;
               case 270:
                  if (curChar != 59)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(292, 297);
                  break;
               case 271:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 272;
                  break;
               case 272:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 273;
                  break;
               case 273:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(292, 297);
                  break;
               case 274:
                  if ((0x27ff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(292, 297);
                  break;
               case 275:
                  if (curChar != 47)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(298, 303);
                  break;
               case 276:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 277;
                  break;
               case 277:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 278;
                  break;
               case 278:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(298, 303);
                  break;
               case 279:
                  if ((0x27ff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(298, 303);
                  break;
               case 280:
                  if (curChar != 59)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(304, 309);
                  break;
               case 281:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 282;
                  break;
               case 282:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 283;
                  break;
               case 283:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(304, 309);
                  break;
               case 284:
                  if ((0x27ff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(304, 309);
                  break;
               case 285:
                  if ((0x2bff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(0, 4);
                  break;
               case 286:
                  if (curChar == 37)
                     jjCheckNAdd(287);
                  break;
               case 287:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 288;
                  break;
               case 288:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(0, 4);
                  break;
               case 289:
                  if (curChar != 47)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(310, 315);
                  break;
               case 290:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 291;
                  break;
               case 291:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 292;
                  break;
               case 292:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(310, 315);
                  break;
               case 293:
                  if ((0x27ff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(310, 315);
                  break;
               case 294:
                  if (curChar != 59)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(316, 321);
                  break;
               case 295:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 296;
                  break;
               case 296:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 297;
                  break;
               case 297:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(316, 321);
                  break;
               case 298:
                  if ((0x27ff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(316, 321);
                  break;
               case 299:
                  if (curChar != 47)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(322, 327);
                  break;
               case 300:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 301;
                  break;
               case 301:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 302;
                  break;
               case 302:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(322, 327);
                  break;
               case 303:
                  if ((0x27ff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(322, 327);
                  break;
               case 304:
                  if (curChar != 59)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(328, 333);
                  break;
               case 305:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 306;
                  break;
               case 306:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 307;
                  break;
               case 307:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(328, 333);
                  break;
               case 308:
                  if ((0x27ff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(328, 333);
                  break;
               case 309:
                  if (curChar == 37)
                     jjCheckNAddTwoStates(310, 287);
                  break;
               case 310:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 311;
                  break;
               case 311:
                  if ((0x3ff000000000000L & l) != 0L && kind > 7)
                     kind = 7;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x47fffffe87ffffffL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAddStates(0, 4);
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(1, 2);
                  break;
               case 1:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(1, 2);
                  break;
               case 4:
                  if ((0x47fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(28, 30);
                  break;
               case 6:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 7:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(28, 30);
                  break;
               case 8:
                  if (curChar == 64)
                     jjAddStates(334, 337);
                  break;
               case 28:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 29:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(35, 40);
                  break;
               case 30:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(35, 40);
                  break;
               case 33:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 34:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(41, 46);
                  break;
               case 35:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(41, 46);
                  break;
               case 38:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 39:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(47, 52);
                  break;
               case 40:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(47, 52);
                  break;
               case 43:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 44:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(53, 58);
                  break;
               case 45:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(53, 58);
                  break;
               case 48:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 49:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(59, 61);
                  break;
               case 50:
                  if ((0x47fffffeafffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(59, 61);
                  break;
               case 53:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 54:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddTwoStates(52, 55);
                  break;
               case 55:
                  if ((0x47fffffeafffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddTwoStates(52, 55);
                  break;
               case 56:
                  if (curChar == 91)
                     jjAddStates(338, 339);
                  break;
               case 58:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(65, 67);
                  break;
               case 59:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(68, 70);
                  break;
               case 60:
               case 66:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(71, 73);
                  break;
               case 61:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(62, 63);
                  break;
               case 62:
                  if (curChar == 93)
                     jjCheckNAdd(24);
                  break;
               case 64:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(74, 76);
                  break;
               case 65:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(77, 79);
                  break;
               case 84:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(80, 85);
                  break;
               case 85:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(86, 88);
                  break;
               case 86:
               case 91:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(89, 91);
                  break;
               case 87:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(62, 88);
                  break;
               case 89:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(92, 94);
                  break;
               case 90:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(95, 97);
                  break;
               case 92:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(98, 100);
                  break;
               case 93:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(101, 103);
                  break;
               case 94:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(95, 108);
                  break;
               case 96:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(104, 106);
                  break;
               case 97:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(107, 109);
                  break;
               case 98:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(110, 112);
                  break;
               case 100:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(116, 118);
                  break;
               case 101:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(119, 121);
                  break;
               case 102:
               case 107:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(122, 124);
                  break;
               case 103:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(62, 104);
                  break;
               case 105:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(125, 127);
                  break;
               case 106:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(128, 130);
                  break;
               case 109:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(340, 343);
                  break;
               case 110:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(110, 111);
                  break;
               case 111:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(112, 24);
                  break;
               case 113:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(133, 135);
                  break;
               case 114:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(114, 115);
                  break;
               case 115:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAdd(116);
                  break;
               case 117:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(136, 140);
                  break;
               case 119:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 120:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(136, 140);
                  break;
               case 125:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 126:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(141, 146);
                  break;
               case 127:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(141, 146);
                  break;
               case 130:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 131:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(147, 152);
                  break;
               case 132:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(147, 152);
                  break;
               case 135:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 136:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(153, 158);
                  break;
               case 137:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(153, 158);
                  break;
               case 140:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 141;
                  break;
               case 141:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(159, 164);
                  break;
               case 142:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(159, 164);
                  break;
               case 144:
               case 147:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAdd(145);
                  break;
               case 145:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(165, 167);
                  break;
               case 148:
                  if ((0x47fffffeafffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(165, 167);
                  break;
               case 149:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(165, 167);
                  break;
               case 151:
                  if ((0x47fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(179, 181);
                  break;
               case 153:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 154:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(179, 181);
                  break;
               case 155:
                  if (curChar == 64)
                     jjAddStates(344, 347);
                  break;
               case 175:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 176;
                  break;
               case 176:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(186, 191);
                  break;
               case 177:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(186, 191);
                  break;
               case 180:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 181;
                  break;
               case 181:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(192, 197);
                  break;
               case 182:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(192, 197);
                  break;
               case 185:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 186;
                  break;
               case 186:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(198, 203);
                  break;
               case 187:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(198, 203);
                  break;
               case 190:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 191;
                  break;
               case 191:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(204, 209);
                  break;
               case 192:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(204, 209);
                  break;
               case 195:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 196;
                  break;
               case 196:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(210, 212);
                  break;
               case 197:
                  if ((0x47fffffeafffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(210, 212);
                  break;
               case 198:
                  if (curChar == 91)
                     jjAddStates(348, 349);
                  break;
               case 200:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(216, 218);
                  break;
               case 201:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(219, 221);
                  break;
               case 202:
               case 208:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(222, 224);
                  break;
               case 203:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(204, 205);
                  break;
               case 204:
                  if (curChar == 93)
                     jjCheckNAdd(171);
                  break;
               case 206:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(225, 227);
                  break;
               case 207:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(228, 230);
                  break;
               case 226:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(231, 236);
                  break;
               case 227:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(237, 239);
                  break;
               case 228:
               case 233:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(240, 242);
                  break;
               case 229:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(204, 230);
                  break;
               case 231:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(243, 245);
                  break;
               case 232:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(246, 248);
                  break;
               case 234:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(249, 251);
                  break;
               case 235:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(252, 254);
                  break;
               case 236:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(237, 250);
                  break;
               case 238:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(255, 257);
                  break;
               case 239:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(258, 260);
                  break;
               case 240:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(261, 263);
                  break;
               case 242:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(267, 269);
                  break;
               case 243:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(270, 272);
                  break;
               case 244:
               case 249:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(273, 275);
                  break;
               case 245:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(204, 246);
                  break;
               case 247:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(276, 278);
                  break;
               case 248:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(279, 281);
                  break;
               case 251:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(350, 353);
                  break;
               case 252:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(252, 253);
                  break;
               case 253:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(254, 171);
                  break;
               case 255:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(284, 286);
                  break;
               case 256:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(256, 257);
                  break;
               case 257:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAdd(258);
                  break;
               case 259:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(287, 291);
                  break;
               case 261:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 262;
                  break;
               case 262:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(287, 291);
                  break;
               case 267:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 268;
                  break;
               case 268:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(5, 10);
                  break;
               case 269:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(5, 10);
                  break;
               case 272:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 273;
                  break;
               case 273:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(292, 297);
                  break;
               case 274:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(292, 297);
                  break;
               case 277:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 278;
                  break;
               case 278:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(298, 303);
                  break;
               case 279:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(298, 303);
                  break;
               case 282:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 283;
                  break;
               case 283:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(304, 309);
                  break;
               case 284:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(304, 309);
                  break;
               case 285:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(0, 4);
                  break;
               case 287:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 288;
                  break;
               case 288:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(0, 4);
                  break;
               case 291:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 292;
                  break;
               case 292:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(310, 315);
                  break;
               case 293:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(310, 315);
                  break;
               case 296:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 297;
                  break;
               case 297:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(316, 321);
                  break;
               case 298:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(316, 321);
                  break;
               case 301:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 302;
                  break;
               case 302:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(322, 327);
                  break;
               case 303:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(322, 327);
                  break;
               case 306:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 307;
                  break;
               case 307:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(328, 333);
                  break;
               case 308:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(328, 333);
                  break;
               case 310:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 311;
                  break;
               case 311:
                  if ((0x7e0000007eL & l) != 0L && kind > 7)
                     kind = 7;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 312 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   286, 285, 289, 193, 51, 266, 269, 270, 275, 193, 51, 1, 2, 122, 123, 143, 
   149, 4, 8, 9, 56, 117, 26, 46, 51, 109, 113, 121, 5, 4, 8, 25, 
   26, 46, 51, 27, 30, 31, 36, 46, 51, 31, 32, 35, 36, 46, 51, 36, 
   37, 40, 41, 46, 51, 36, 41, 42, 45, 46, 51, 47, 50, 51, 58, 82, 
   62, 59, 62, 63, 60, 62, 63, 61, 62, 63, 65, 62, 63, 66, 62, 63, 
   85, 92, 95, 108, 62, 88, 86, 62, 88, 87, 62, 88, 90, 62, 88, 91, 
   62, 88, 93, 95, 108, 94, 95, 108, 95, 97, 108, 95, 98, 108, 95, 94, 
   108, 100, 82, 62, 101, 62, 104, 102, 62, 104, 103, 62, 104, 106, 62, 104, 
   107, 62, 104, 110, 111, 114, 115, 116, 118, 117, 26, 46, 51, 124, 127, 128, 
   133, 46, 51, 128, 129, 132, 133, 46, 51, 133, 134, 137, 138, 46, 51, 133, 
   138, 139, 142, 46, 51, 146, 148, 51, 151, 155, 156, 198, 259, 173, 193, 51, 
   251, 255, 263, 152, 151, 155, 172, 173, 193, 51, 174, 177, 178, 183, 193, 51, 
   178, 179, 182, 183, 193, 51, 183, 184, 187, 188, 193, 51, 183, 188, 189, 192, 
   193, 51, 194, 197, 51, 200, 224, 204, 201, 204, 205, 202, 204, 205, 203, 204, 
   205, 207, 204, 205, 208, 204, 205, 227, 234, 237, 250, 204, 230, 228, 204, 230, 
   229, 204, 230, 232, 204, 230, 233, 204, 230, 235, 237, 250, 236, 237, 250, 237, 
   239, 250, 237, 240, 250, 237, 236, 250, 242, 224, 204, 243, 204, 246, 244, 204, 
   246, 245, 204, 246, 248, 204, 246, 249, 204, 246, 252, 253, 256, 257, 258, 260, 
   259, 173, 193, 51, 270, 271, 274, 275, 193, 51, 275, 276, 279, 280, 193, 51, 
   275, 280, 281, 284, 193, 51, 290, 293, 294, 299, 193, 51, 294, 295, 298, 299, 
   193, 51, 299, 300, 303, 304, 193, 51, 299, 304, 305, 308, 193, 51, 9, 56, 
   109, 113, 83, 84, 110, 111, 112, 24, 156, 198, 251, 255, 225, 226, 252, 253, 
   254, 171, 
};
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, };
public static final String[] lexStateNames = {
   "DEFAULT", 
};
private ASCII_CharStream input_stream;
private final int[] jjrounds = new int[312];
private final int[] jjstateSet = new int[624];
protected char curChar;
public UriReferenceParserTokenManager(ASCII_CharStream stream)
{
   if (ASCII_CharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public UriReferenceParserTokenManager(ASCII_CharStream stream, int lexState)
{
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(ASCII_CharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 312; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(ASCII_CharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

private final Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public final Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
         matchedToken = jjFillToken();
         return matchedToken;
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

}
