/* Generated By:JavaCC: Do not edit this line. UriReferenceParserConstants.java */
package com.sun.tranquilo.datatype;

public interface UriReferenceParserConstants {

  int EOF = 0;
  int digit = 1;
  int loalpha = 2;
  int upalpha = 3;
  int alpha = 4;
  int alphanum = 5;
  int hex = 6;
  int escaped = 7;
  int mark = 8;
  int unreserved = 9;
  int reserved = 10;
  int uric = 11;
  int fragment = 12;
  int query = 13;
  int pchar = 14;
  int param = 15;
  int segment = 16;
  int path_segments = 17;
  int path = 18;
  int port = 19;
  int __upTo3digit = 20;
  int IPv4address = 21;
  int hex4 = 22;
  int hexseq = 23;
  int hexpart = 24;
  int IPv6address = 25;
  int IPv6reference = 26;
  int domainlabel = 27;
  int toplabel = 28;
  int hostname = 29;
  int host = 30;
  int hostport = 31;
  int userinfo = 32;
  int server = 33;
  int reg_name = 34;
  int authority = 35;
  int scheme = 36;
  int rel_segment = 37;
  int abs_path = 38;
  int rel_path = 39;
  int net_path = 40;
  int uric_no_slash = 41;
  int opaque_part = 42;
  int hier_part = 43;
  int relativeURI = 44;
  int absoluteURI = 45;
  int uriReference = 46;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<digit>",
    "<loalpha>",
    "<upalpha>",
    "<alpha>",
    "<alphanum>",
    "<hex>",
    "<escaped>",
    "<mark>",
    "<unreserved>",
    "<reserved>",
    "<uric>",
    "<fragment>",
    "<query>",
    "<pchar>",
    "<param>",
    "<segment>",
    "<path_segments>",
    "<path>",
    "<port>",
    "<__upTo3digit>",
    "<IPv4address>",
    "<hex4>",
    "<hexseq>",
    "<hexpart>",
    "<IPv6address>",
    "<IPv6reference>",
    "<domainlabel>",
    "<toplabel>",
    "<hostname>",
    "<host>",
    "<hostport>",
    "<userinfo>",
    "<server>",
    "<reg_name>",
    "<authority>",
    "<scheme>",
    "<rel_segment>",
    "<abs_path>",
    "<rel_path>",
    "<net_path>",
    "<uric_no_slash>",
    "<opaque_part>",
    "<hier_part>",
    "<relativeURI>",
    "<absoluteURI>",
    "<uriReference>",
  };

}
