package com.sun.tranquilo.schema;

import jp.gr.xml.formal.automaton.Automaton;
import jp.gr.xml.formal.automaton.AutomatonFactory;

/**
 * object that contains one HedgeModel
 */
public abstract class ModelParent implements Model
{
	/** child (the hedge model that this object holds) */
	protected HedgeModel hedgeModel;
	
	final public Automaton getAutomaton( AutomatonFactory factory )
	{// simply returns the automaton generated by child		
		return hedgeModel.getAutomaton(factory);
	}
	
	/** gets the child */
	public HedgeModel getHedgeModel() { return hedgeModel; }
	/** sets the child */
	public void setHedgeModel( HedgeModel hm )
	{
		if( hm==null )	throw new IllegalArgumentException();
		hedgeModel = hm;
	}
	
	protected ModelParent( HedgeModel child )
	{
		setHedgeModel(child);
	}
}
